name: Python Test Workflow - Database Service

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov pymongo

      # Step 4: Run pytest
      - name: Run pytest with coverage
        run: |
          cd db-service  # 确保进入正确的目录
          pytest test_db_service.py --cov=db_service --cov-report=xml --cov-report=term-missing
