name: Python Test Workflow - Database Service

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov pymongo

      # Step 4: Setup MongoDB
      - name: Setup MongoDB
        uses: supercharge/mongodb-github-action@1.5.0
        with:
          mongodb-version: '5.0'

      # Step 5: Run pytest with coverage
      - name: Run pytest with coverage
        run: |
          pytest test_db_service.py --cov=db_service --cov-report=xml --cov-report=term-missing

      # Step 6: Upload coverage report (optional)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
          flags: db-service
          name: codecov-coverage-report-db-service
