name: Python Test Workflow - Database Service

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          cd db-service
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run pytest with coverage
      - name: Run pytest with coverage
        run: |
          cd db-service
          pytest test_db_service.py --cov=db_service --cov-report=xml --cov-report=term-missing
